In [101]:
#https://github.com/pjustus/geopython-final-ex-2021

In [67]:
# Importing modules
import pandas as pd
import datetime

In [51]:
# Reading data
fp = "data/2315676.txt"
data = pd.read_csv(fp, skiprows=[1], delim_whitespace=True, parse_dates=["DATE"])
print(data)

                 STATION      STATION_NAME       DATE  TAVG  TMAX  TMIN
0      GHCND:FI000007501  SODANKYLA-AWS-FI 1908-01-01 -9999     2   -37
1      GHCND:FI000007501  SODANKYLA-AWS-FI 1908-01-02 -9999     6   -26
2      GHCND:FI000007501  SODANKYLA-AWS-FI 1908-01-03 -9999     7   -27
3      GHCND:FI000007501  SODANKYLA-AWS-FI 1908-01-04 -9999    -3   -27
4      GHCND:FI000007501  SODANKYLA-AWS-FI 1908-01-05 -9999     4   -36
...                  ...               ...        ...   ...   ...   ...
41060  GHCND:FI000007501  SODANKYLA-AWS-FI 2020-10-03    47    51 -9999
41061  GHCND:FI000007501  SODANKYLA-AWS-FI 2020-10-04    43    47    37
41062  GHCND:FI000007501  SODANKYLA-AWS-FI 2020-10-05    42 -9999    37
41063  GHCND:FI000007501  SODANKYLA-AWS-FI 2020-10-06    45    46    43
41064  GHCND:FI000007501  SODANKYLA-AWS-FI 2020-10-07    47    50    44

[41065 rows x 6 columns]

In [52]:
data["TEMP_CELSIUS"] = (data["TAVG"] - 32) / (9 / 5)
data["TEMP_KELVIN"] = data["TAVG"] + 273.15
data

,STATION,STATION_NAME,DATE,TAVG,TMAX,TMIN,TEMP_CELSIUS,TEMP_KELVIN
0,GHCND:FI000007501,SODANKYLA-AWS-FI,1908-01-01,-9999,2,-37,-5572.777778,-9725.85
1,GHCND:FI000007501,SODANKYLA-AWS-FI,1908-01-02,-9999,6,-26,-5572.777778,-9725.85
2,GHCND:FI000007501,SODANKYLA-AWS-FI,1908-01-03,-9999,7,-27,-5572.777778,-9725.85
3,GHCND:FI000007501,SODANKYLA-AWS-FI,1908-01-04,-9999,-3,-27,-5572.777778,-9725.85
4,GHCND:FI000007501,SODANKYLA-AWS-FI,1908-01-05,-9999,4,-36,-5572.777778,-9725.85
...,...,...,...,...,...,...,...,...
41060,GHCND:FI000007501,SODANKYLA-AWS-FI,2020-10-03,47,51,-9999,8.333333,320.15
41061,GHCND:FI000007501,SODANKYLA-AWS-FI,2020-10-04,43,47,37,6.111111,316.15
41062,GHCND:FI000007501,SODANKYLA-AWS-FI,2020-10-05,42,-9999,37,5.555556,315.15
41063,GHCND:FI000007501,SODANKYLA-AWS-FI,2020-10-06,45,46,43,7.222222,318.15
41064,GHCND:FI000007501,SODANKYLA-AWS-FI,2020-10-07,47,50,44,8.333333,320.15

In [100]:
#data.loc[(data['DATE'].dt.month==6)].tail(7)
# LESSON 6 NEXT